-- Generated by tools/intro/build_audio.ps1. Do not edit by hand.
-- introLength: narration length of each scene in seconds; introCues: when each key phrase appears.
local ADDON, ST = ...
ST.introLength = { 22.10, 9.80, 26.40, 24.70, 21.90, 12.50, 14.00, 14.30 }
ST.introCues = {
    [1] = {
        { t = 0.55, text = "THE COSMIC INDEX OF SUMMONABLE PERSONS" },
        { t = 7.91, text = "NOBODY HAS EVER READ IT" },
        { t = 16.61, text = "ONE CLERK" },
        { t = 20.01, text = "9,000 YEARS ON SHIFT" },
    },
    [2] = {
        { t = 2.31, text = "ACHOO." },
        { t = 7.08, text = "THE ORIGIN OF THE PROBLEM" },
    },
    [3] = {
        { t = 2.21, text = "LICENSED SUMMONING LIAISON, 3RD CLASS" },
        { t = 8.07, text = "DEFAULT RECIPIENT" },
        { t = 19.85, text = "RITUALS MEANT FOR NOBODY" },
        { t = 24.29, text = "ONE WAS FOR A GOAT" },
    },
    [4] = {
        { t = 4.80, text = "SEARCHING FOR: THE FORM" },
        { t = 9.55, text = "FORM 27B/6" },
        { t = 14.01, text = "NEVER SEEN" },
        { t = 21.79, text = "EXACTLY WHAT A FORM WOULD SAY" },
    },
    [5] = {
        { t = 5.50, text = "A FRAGILE SENSE OF SELF" },
        { t = 14.41, text = "ATTENTION. CLOSURE." },
        { t = 19.12, text = "FIFTY SILVER" },
    },
    [6] = {
        { t = 3.46, text = "INSTALLMENT ON A DEBT" },
        { t = 5.32, text = "NEVER AGREED TO" },
        { t = 10.30, text = "DEFINITE PROGRESS" },
    },
    [7] = {
        { t = 5.22, text = "VERY EASY TO SUMMON" },
        { t = 8.46, text = "NO OBJECTION" },
        { t = 11.87, text = "NEVER ASKED" },
    },
    [8] = {
        { t = 2.38, text = "THE WEEK AFTER THAT" },
        { t = 8.88, text = "OR THE LAST" },
        { t = 11.71, text = "THE INDEX IS UNCLEAR" },
    },
}
-- introSentences: when each sentence of the narration starts, for the subtitles.
ST.introSentences = {
    [1] = {
        { t = 0.42, text = [=[The Cosmic Index of Summonable Persons is, by general agreement, the most important document in Azeroth that nobody has ever read.]=] },
        { t = 10.41, text = [=[It lists every being that may legally be summoned, in alphabetical order, and it was compiled by a single clerk who had, at the time, been on shift for nine thousand years.]=] },
    },
    [2] = {
        { t = 0.41, text = [=[Somewhere around the letter Zed, the clerk sneezed.]=] },
        { t = 4.80, text = [=[This is generally accepted to be the origin of the entire problem.]=] },
    },
    [3] = {
        { t = 0.41, text = [=[As a result of the sneeze, a Licensed Summoning Liaison, Third Class, named Zenit was entered into the Index as the default recipient of every Ritual of Summoning completed within range of his name.]=] },
        { t = 14.60, text = [=[This includes rituals meant for other people.]=] },
        { t = 18.65, text = [=[It includes rituals meant for nobody.]=] },
        { t = 22.38, text = [=[It includes at least one ritual intended for a goat.]=] },
    },
    [4] = {
        { t = 0.41, text = [=[Zenit did what any reasonable person would do.]=] },
        { t = 4.76, text = [=[He looked for the form.]=] },
        { t = 7.47, text = [=[The form turned out to be Form 27B slash 6, which is referenced throughout the Index and has never been seen.]=] },
        { t = 16.18, text = [=[Several scholars believe it does not exist.]=] },
        { t = 20.34, text = [=[Zenit believes that is exactly what a form would say.]=] },
    },
    [5] = {
        { t = 0.41, text = [=[Meanwhile, the Ritual of Summoning, a spell with a great deal of free time and a fragile sense of self, had formed an attachment.]=] },
        { t = 9.63, text = [=[It does not want gold.]=] },
        { t = 12.53, text = [=[It wants, in its own words, attention and closure.]=] },
        { t = 17.38, text = [=[It will, however, accept fifty silver as a gesture.]=] },
    },
    [6] = {
        { t = 0.42, text = [=[And so every completed summon is recorded as an installment on a debt Zenit never agreed to, cannot find the paperwork for, and is nevertheless making definite progress on.]=] },
    },
    [7] = {
        { t = 0.42, text = [=[You, meanwhile, are a party of friends who have noticed that Zenit is, technically, very easy to summon.]=] },
        { t = 7.43, text = [=[The Index has no objection.]=] },
        { t = 10.94, text = [=[The Index has never been asked.]=] },
    },
    [8] = {
        { t = 0.41, text = [=[This is the story of his week, and the week after that.]=] },
        { t = 4.62, text = [=[If the form is ever found, you will be the first to know.]=] },
        { t = 9.03, text = [=[Or the last.]=] },
        { t = 11.44, text = [=[The Index is unclear.]=] },
    },
}
