-- Generated by tools/intro/build_audio.ps1. Do not edit by hand.
-- introLength: narration length of each scene in seconds; introCues: when each key phrase appears.
local ADDON, ST = ...
ST.introEnding = 3.20
ST.introLength = { 22.10, 9.80, 26.40, 24.70, 21.90, 12.50, 14.00, 14.30, 26.70, 25.50, 24.70, 32.00 }
ST.introCues = {
    [1] = {
        { t = 0.55, text = "THE COSMIC INDEX OF SUMMONABLE PERSONS" },
        { t = 7.91, text = "NOBODY HAS EVER READ IT" },
        { t = 16.61, text = "ONE CLERK" },
        { t = 20.01, text = "9,000 YEARS ON SHIFT" },
    },
    [2] = {
        { t = 2.26, text = "ACHOO." },
        { t = 7.08, text = "THE ORIGIN OF THE PROBLEM" },
    },
    [3] = {
        { t = 2.20, text = "LICENSED SUMMONING LIAISON, 3RD CLASS" },
        { t = 8.09, text = "DEFAULT RECIPIENT" },
        { t = 19.85, text = "RITUALS MEANT FOR NOBODY" },
        { t = 24.29, text = "ONE WAS FOR A GOAT" },
    },
    [4] = {
        { t = 4.80, text = "SEARCHING FOR: THE FORM" },
        { t = 9.55, text = "FORM 27B/6" },
        { t = 14.01, text = "NEVER SEEN" },
        { t = 21.83, text = "EXACTLY WHAT A FORM WOULD SAY" },
    },
    [5] = {
        { t = 5.50, text = "A FRAGILE SENSE OF SELF" },
        { t = 14.41, text = "ATTENTION. CLOSURE." },
        { t = 19.12, text = "FIFTY SILVER" },
    },
    [6] = {
        { t = 3.44, text = "INSTALLMENT ON A DEBT" },
        { t = 5.36, text = "NEVER AGREED TO" },
        { t = 10.31, text = "DEFINITE PROGRESS" },
    },
    [7] = {
        { t = 5.23, text = "VERY EASY TO SUMMON" },
        { t = 8.46, text = "NO OBJECTION" },
        { t = 11.87, text = "NEVER ASKED" },
    },
    [8] = {
        { t = 2.38, text = "THE WEEK AFTER THAT" },
        { t = 8.88, text = "OR THE LAST" },
        { t = 11.71, text = "THE INDEX IS UNCLEAR" },
    },
    [9] = {
        { t = 4.73, text = "THE GROUP EARNS POINTS" },
        { t = 9.29, text = "REMOTE. DANGEROUS. UNREASONABLE." },
        { t = 14.82, text = "ZENNIT'S SECRET LIST" },
        { t = 24.48, text = "VICTORY FOR PERSISTENCE" },
    },
    [10] = {
        { t = 2.47, text = "ZENNIT WINS THE WEEK" },
        { t = 5.09, text = "IMMUNE FOR 7 DAYS" },
        { t = 7.78, text = "HE MAY REFUSE" },
        { t = 11.33, text = "50 SILVER. CASH. NO RECEIPT." },
        { t = 16.06, text = "OR DICE" },
        { t = 23.14, text = "THE INDEX ACCEPTS MOST THINGS" },
    },
    [11] = {
        { t = 1.70, text = "THE INDEX COUNTED" },
        { t = 13.90, text = "ZENNIT HAD WON" },
        { t = 16.95, text = "HE WON THE DICE" },
        { t = 22.75, text = "SEVERAL PLACES ON HIS LIST" },
    },
    [12] = {
        { t = 2.02, text = "BY REGISTERED LETTER" },
        { t = 7.26, text = "SEVEN DAYS. NO RITUAL COULD FIND HIM." },
        { t = 19.16, text = "ON LEAVE" },
        { t = 21.85, text = "DOING NOTHING AT ALL" },
        { t = 30.10, text = "ACHOO. AGAIN." },
    },
}
-- introSentences: when each sentence of the narration starts, for the subtitles.
ST.introSentences = {
    [1] = {
        { t = 0.42, text = [=[The Cosmic Index of Summonable Persons is, by general agreement, the most important document in Azeroth that nobody has ever read.]=] },
        { t = 10.41, text = [=[It lists every being that may legally be summoned, in alphabetical order, and it was compiled by a single clerk who had, at the time, been on shift for nine thousand years.]=] },
    },
    [2] = {
        { t = 0.41, text = [=[Somewhere around the letter Z, the clerk sneezed.]=] },
        { t = 4.80, text = [=[This is generally accepted to be the origin of the entire problem.]=] },
    },
    [3] = {
        { t = 0.41, text = [=[As a result of the sneeze, a Licensed Summoning Liaison, Third Class, named Zennit was entered into the Index as the default recipient of every Ritual of Summoning completed within range of his name.]=] },
        { t = 14.60, text = [=[This includes rituals meant for other people.]=] },
        { t = 18.65, text = [=[It includes rituals meant for nobody.]=] },
        { t = 22.38, text = [=[It includes at least one ritual intended for a goat.]=] },
    },
    [4] = {
        { t = 0.41, text = [=[Zennit did what any reasonable person would do.]=] },
        { t = 4.76, text = [=[He looked for the form.]=] },
        { t = 7.47, text = [=[The form turned out to be Form 27B slash 6, which is referenced throughout the Index and has never been seen.]=] },
        { t = 16.18, text = [=[Several scholars believe it does not exist.]=] },
        { t = 20.34, text = [=[Zennit believes that is exactly what a form would say.]=] },
    },
    [5] = {
        { t = 0.41, text = [=[Meanwhile, the Ritual of Summoning, a spell with a great deal of free time and a fragile sense of self, had formed an attachment.]=] },
        { t = 9.63, text = [=[It does not want gold.]=] },
        { t = 12.53, text = [=[It wants, in its own words, attention and closure.]=] },
        { t = 17.38, text = [=[It will, however, accept fifty silver as a gesture.]=] },
    },
    [6] = {
        { t = 0.42, text = [=[And so every completed summon is recorded as an installment on a debt Zennit never agreed to, cannot find the paperwork for, and is nevertheless making definite progress on.]=] },
    },
    [7] = {
        { t = 0.42, text = [=[You, meanwhile, are a party of friends who have noticed that Zennit is, technically, very easy to summon.]=] },
        { t = 7.43, text = [=[The Index has no objection.]=] },
        { t = 10.94, text = [=[The Index has never been asked.]=] },
    },
    [8] = {
        { t = 0.41, text = [=[This is the story of his week, and the week after that.]=] },
        { t = 4.62, text = [=[If the form is ever found, you will be the first to know.]=] },
        { t = 9.03, text = [=[Or the last.]=] },
        { t = 11.44, text = [=[The Index is unclear.]=] },
    },
    [9] = {
        { t = 0.40, text = [=[The rules, such as they are.]=] },
        { t = 3.53, text = [=[Each week, the group earns points by summoning Zennit, with more points for places that are remote, or dangerous, or frankly unreasonable.]=] },
        { t = 13.25, text = [=[Zennit, for his part, holds a secret list, which he may complete at any time, and which he will not discuss.]=] },
        { t = 20.34, text = [=[If the group has more points at the end of the week, the Index records a victory for persistence.]=] },
    },
    [10] = {
        { t = 0.40, text = [=[If Zennit completes his list first, he wins the week, and cannot be summoned for the seven days that follow.]=] },
        { t = 7.42, text = [=[He may refuse a summons.]=] },
        { t = 10.42, text = [=[He may demand fifty silver, in cash, with no receipt.]=] },
        { t = 15.32, text = [=[Or he may suggest dice.]=] },
        { t = 18.59, text = [=[The Index will accept any of these.]=] },
        { t = 22.52, text = [=[The Index accepts most things.]=] },
    },
    [11] = {
        { t = 0.41, text = [=[At the end of the week, the Index counted.]=] },
        { t = 4.16, text = [=[It counted the summons, and the places, and the refusals, and the dice, and then it counted them again, because the total was not the one it had expected.]=] },
        { t = 14.05, text = [=[Zennit had won.]=] },
        { t = 16.68, text = [=[He had won the dice when it mattered, and he had been summoned, entirely by accident, to several of the places on his list.]=] },
    },
    [12] = {
        { t = 0.40, text = [=[The Index informed Zennit by registered letter, which he did not trust, and which he read twice.]=] },
        { t = 7.14, text = [=[For seven days, no ritual could find him.]=] },
        { t = 11.14, text = [=[The party gathered in a circle and said his name, and the Index replied that the Licensed Summoning Liaison was, regrettably, on leave.]=] },
        { t = 20.77, text = [=[Zennit spent the week doing nothing at all, which he had always suspected to be the correct amount.]=] },
        { t = 27.20, text = [=[On the eighth day, somewhere around the letter Z, the clerk sneezed.]=] },
    },
}
-- introHighlights: while something is mentioned, a box is drawn round it (x, y, w, h in the 960x540 picture).
ST.introHighlights = {
    [1] = {
        { t = 0.65, x = 684, y = 244, w = 222, h = 297 },
        { t = 16.71, x = 322, y = 344, w = 120, h = 158 },
        { t = 20.11, x = 322, y = 344, w = 120, h = 158 },
    },
    [2] = {
        { t = 1.72, x = 612, y = 192, w = 216, h = 156 },
        { t = 2.36, x = 30, y = 10, w = 380, h = 520 },
    },
    [3] = {
        { t = 5.05, x = 696, y = 56, w = 208, h = 300 },
        { t = 16.56, x = 26, y = 166, w = 198, h = 216 },
        { t = 19.95, x = 246, y = 166, w = 198, h = 216 },
        { t = 24.39, x = 466, y = 166, w = 198, h = 216 },
    },
    [4] = {
        { t = 4.90, x = 108, y = 128, w = 272, h = 380 },
        { t = 9.65, x = 690, y = 140, w = 140, h = 185 },
    },
    [5] = {
        { t = 1.33, x = 250, y = 20, w = 460, h = 500 },
        { t = 14.51, x = 730, y = 50, w = 170, h = 140 },
        { t = 19.22, x = 30, y = 324, w = 210, h = 226 },
    },
    [6] = {
        { t = 3.54, x = 244, y = 30, w = 472, h = 480 },
        { t = 5.46, x = 26, y = 224, w = 176, h = 240 },
    },
    [7] = {
        { t = 1.65, x = 50, y = 224, w = 520, h = 236 },
        { t = 3.93, x = 754, y = 124, w = 212, h = 290 },
        { t = 8.56, x = 556, y = 226, w = 200, h = 260 },
    },
    [8] = {
        { t = 1.09, x = 344, y = 0, w = 376, h = 524 },
        { t = 5.01, x = 640, y = 50, w = 150, h = 200 },
        { t = 11.81, x = 24, y = 374, w = 132, h = 172 },
    },
    [9] = {
        { t = 4.83, x = 36, y = 56, w = 236, h = 278 },
        { t = 7.33, x = 36, y = 356, w = 456, h = 78 },
        { t = 9.39, x = 376, y = 356, w = 112, h = 78 },
        { t = 14.92, x = 500, y = 50, w = 240, h = 400 },
        { t = 24.58, x = 36, y = 56, w = 448, h = 278 },
    },
    [10] = {
        { t = 2.57, x = 36, y = 96, w = 272, h = 380 },
        { t = 7.88, x = 326, y = 86, w = 188, h = 258 },
        { t = 11.43, x = 516, y = 86, w = 188, h = 258 },
        { t = 16.16, x = 706, y = 86, w = 188, h = 258 },
        { t = 23.24, x = 326, y = 356, w = 426, h = 140 },
    },
    [11] = {
        { t = 1.80, x = 40, y = 60, w = 440, h = 270 },
        { t = 14.00, x = 262, y = 140, w = 220, h = 170 },
        { t = 17.05, x = 50, y = 365, w = 150, h = 100 },
        { t = 22.85, x = 500, y = 50, w = 240, h = 400 },
    },
    [12] = {
        { t = 2.12, x = 24, y = 110, w = 176, h = 150 },
        { t = 7.36, x = 296, y = 26, w = 392, h = 60 },
        { t = 13.36, x = 340, y = 140, w = 170, h = 66 },
        { t = 19.26, x = 556, y = 104, w = 182, h = 84 },
        { t = 21.95, x = 766, y = 200, w = 170, h = 280 },
        { t = 30.20, x = 16, y = 330, w = 200, h = 210 },
    },
}
