-- Generated by tools/intro/build_audio.ps1. Do not edit by hand.
-- introLength: narration length of each scene in seconds; introCues: when each key phrase appears.
local ADDON, ST = ...
ST.introEnding = 3.20
ST.introLength = { 22.10, 9.80, 26.40, 24.70, 21.90, 12.50, 14.00, 14.30, 26.70, 25.50, 24.70, 27.00, 27.70, 26.50, 25.90, 29.80, 27.60, 29.40 }
ST.introCues = {
    [1] = {
        { t = 0.55, text = "THE COSMIC INDEX OF SUMMONABLE PERSONS" },
        { t = 7.91, text = "NOBODY HAS EVER READ IT" },
        { t = 16.61, text = "ONE CLERK" },
        { t = 20.01, text = "9,000 YEARS ON SHIFT" },
    },
    [2] = {
        { t = 2.26, text = "ACHOO." },
        { t = 7.08, text = "THE ORIGIN OF THE PROBLEM" },
    },
    [3] = {
        { t = 2.20, text = "LICENSED SUMMONING LIAISON, 3RD CLASS" },
        { t = 8.09, text = "DEFAULT RECIPIENT" },
        { t = 19.85, text = "RITUALS MEANT FOR NOBODY" },
        { t = 24.29, text = "ONE WAS FOR A GOAT" },
    },
    [4] = {
        { t = 4.80, text = "SEARCHING FOR: THE FORM" },
        { t = 9.55, text = "FORM 27B/6" },
        { t = 14.01, text = "NEVER SEEN" },
        { t = 21.83, text = "EXACTLY WHAT A FORM WOULD SAY" },
    },
    [5] = {
        { t = 5.50, text = "A FRAGILE SENSE OF SELF" },
        { t = 14.41, text = "ATTENTION. CLOSURE." },
        { t = 19.12, text = "FIFTY SILVER" },
    },
    [6] = {
        { t = 3.44, text = "INSTALLMENT ON A DEBT" },
        { t = 5.36, text = "NEVER AGREED TO" },
        { t = 10.31, text = "DEFINITE PROGRESS" },
    },
    [7] = {
        { t = 5.23, text = "VERY EASY TO SUMMON" },
        { t = 8.46, text = "NO OBJECTION" },
        { t = 11.87, text = "NEVER ASKED" },
    },
    [8] = {
        { t = 2.38, text = "THE WEEK AFTER THAT" },
        { t = 8.88, text = "OR THE LAST" },
        { t = 11.71, text = "THE INDEX IS UNCLEAR" },
    },
    [9] = {
        { t = 4.73, text = "THE GROUP EARNS POINTS" },
        { t = 9.29, text = "REMOTE. DANGEROUS. UNREASONABLE." },
        { t = 14.82, text = "ZENNIT'S SECRET LIST" },
        { t = 24.48, text = "VICTORY FOR PERSISTENCE" },
    },
    [10] = {
        { t = 2.47, text = "ZENNIT WINS THE WEEK" },
        { t = 5.09, text = "IMMUNE FOR 7 DAYS" },
        { t = 7.78, text = "HE MAY REFUSE" },
        { t = 11.33, text = "50 SILVER. CASH. NO RECEIPT." },
        { t = 16.06, text = "OR DICE" },
        { t = 23.14, text = "THE INDEX ACCEPTS MOST THINGS" },
    },
    [11] = {
        { t = 1.70, text = "THE INDEX COUNTED" },
        { t = 13.90, text = "ZENNIT HAD WON" },
        { t = 16.95, text = "HE WON THE DICE" },
        { t = 22.75, text = "SEVERAL PLACES ON HIS LIST" },
    },
    [12] = {
        { t = 2.03, text = "BY REGISTERED LETTER" },
        { t = 7.26, text = "SEVEN DAYS. NO RITUAL COULD FIND HIM." },
        { t = 19.15, text = "ON LEAVE" },
        { t = 21.87, text = "DOING NOTHING AT ALL" },
    },
    [13] = {
        { t = 1.53, text = "THE GROUP WON" },
        { t = 4.38, text = "NOBODY MORE SURPRISED" },
        { t = 15.75, text = "DESPITE THE HEAD START" },
        { t = 23.59, text = "CHECKED THREE TIMES" },
    },
    [14] = {
        { t = 0.38, text = "A VICTORY FOR PERSISTENCE" },
        { t = 15.24, text = "A SMALL CAKE" },
        { t = 16.60, text = "WHICH HE DID NOT TRUST" },
        { t = 24.43, text = "COUNTING THE NEXT ONE" },
    },
    [15] = {
        { t = 3.65, text = "A PARCEL" },
        { t = 6.29, text = "A BRASS KEY" },
        { t = 8.60, text = "SIDE DOOR" },
        { t = 17.81, text = "THE FIRST ITEM" },
        { t = 23.06, text = "TOO BUSY BEING SUMMONED" },
    },
    [16] = {
        { t = 4.67, text = "BEHIND THE LETTER Q" },
        { t = 8.84, text = "PLEASE DO NOT" },
        { t = 15.23, text = "A VERY OLD KETTLE" },
        { t = 18.27, text = "A CHAIR THAT FIT HIM" },
        { t = 27.88, text = "SOMEONE CLEARED HIS THROAT" },
    },
    [17] = {
        { t = 2.87, text = "AN UNEXPECTED RECEIPT" },
        { t = 9.72, text = "BLUE CARBON PAPER" },
        { t = 15.18, text = "THE TITLE WAS SMUDGED" },
        { t = 21.37, text = "FORM 27B/6" },
    },
    [18] = {
        { t = 3.02, text = "THE FORM DID NOT EXIST" },
        { t = 13.15, text = "IN TRIPLICATE" },
        { t = 20.63, text = "THE PARTY KEPT THE THIRD" },
        { t = 27.73, text = "THEY WILL THINK ABOUT IT" },
    },
}
-- introSentences: when each sentence of the narration starts, for the subtitles.
ST.introSentences = {
    [1] = {
        { t = 0.42, text = [=[The Cosmic Index of Summonable Persons is, by general agreement, the most important document in Azeroth that nobody has ever read.]=] },
        { t = 10.41, text = [=[It lists every being that may legally be summoned, in alphabetical order, and it was compiled by a single clerk who had, at the time, been on shift for nine thousand years.]=] },
    },
    [2] = {
        { t = 0.41, text = [=[Somewhere around the letter Z, the clerk sneezed.]=] },
        { t = 4.80, text = [=[This is generally accepted to be the origin of the entire problem.]=] },
    },
    [3] = {
        { t = 0.41, text = [=[As a result of the sneeze, a Licensed Summoning Liaison, Third Class, named Zennit was entered into the Index as the default recipient of every Ritual of Summoning completed within range of his name.]=] },
        { t = 14.60, text = [=[This includes rituals meant for other people.]=] },
        { t = 18.65, text = [=[It includes rituals meant for nobody.]=] },
        { t = 22.38, text = [=[It includes at least one ritual intended for a goat.]=] },
    },
    [4] = {
        { t = 0.41, text = [=[Zennit did what any reasonable person would do.]=] },
        { t = 4.76, text = [=[He looked for the form.]=] },
        { t = 7.47, text = [=[The form turned out to be Form 27B slash 6, which is referenced throughout the Index and has never been seen.]=] },
        { t = 16.18, text = [=[Several scholars believe it does not exist.]=] },
        { t = 20.34, text = [=[Zennit believes that is exactly what a form would say.]=] },
    },
    [5] = {
        { t = 0.41, text = [=[Meanwhile, the Ritual of Summoning, a spell with a great deal of free time and a fragile sense of self, had formed an attachment.]=] },
        { t = 9.63, text = [=[It does not want gold.]=] },
        { t = 12.53, text = [=[It wants, in its own words, attention and closure.]=] },
        { t = 17.38, text = [=[It will, however, accept fifty silver as a gesture.]=] },
    },
    [6] = {
        { t = 0.42, text = [=[And so every completed summon is recorded as an installment on a debt Zennit never agreed to, cannot find the paperwork for, and is nevertheless making definite progress on.]=] },
    },
    [7] = {
        { t = 0.42, text = [=[You, meanwhile, are a party of friends who have noticed that Zennit is, technically, very easy to summon.]=] },
        { t = 7.43, text = [=[The Index has no objection.]=] },
        { t = 10.94, text = [=[The Index has never been asked.]=] },
    },
    [8] = {
        { t = 0.41, text = [=[This is the story of his week, and the week after that.]=] },
        { t = 4.62, text = [=[If the form is ever found, you will be the first to know.]=] },
        { t = 9.03, text = [=[Or the last.]=] },
        { t = 11.44, text = [=[The Index is unclear.]=] },
    },
    [9] = {
        { t = 0.40, text = [=[The rules, such as they are.]=] },
        { t = 3.53, text = [=[Each week, the group earns points by summoning Zennit, with more points for places that are remote, or dangerous, or frankly unreasonable.]=] },
        { t = 13.25, text = [=[Zennit, for his part, holds a secret list, which he may complete at any time, and which he will not discuss.]=] },
        { t = 20.34, text = [=[If the group has more points at the end of the week, the Index records a victory for persistence.]=] },
    },
    [10] = {
        { t = 0.40, text = [=[If Zennit completes his list first, he wins the week, and cannot be summoned for the seven days that follow.]=] },
        { t = 7.42, text = [=[He may refuse a summons.]=] },
        { t = 10.42, text = [=[He may demand fifty silver, in cash, with no receipt.]=] },
        { t = 15.32, text = [=[Or he may suggest dice.]=] },
        { t = 18.59, text = [=[The Index will accept any of these.]=] },
        { t = 22.52, text = [=[The Index accepts most things.]=] },
    },
    [11] = {
        { t = 0.41, text = [=[At the end of the week, the Index counted.]=] },
        { t = 4.16, text = [=[It counted the summons, and the places, and the refusals, and the dice, and then it counted them again, because the total was not the one it had expected.]=] },
        { t = 14.05, text = [=[Zennit had won.]=] },
        { t = 16.68, text = [=[He had won the dice when it mattered, and he had been summoned, entirely by accident, to several of the places on his list.]=] },
    },
    [12] = {
        { t = 0.41, text = [=[The Index informed Zennit by registered letter, which he did not trust, and which he read twice.]=] },
        { t = 7.14, text = [=[For seven days, no ritual could find him.]=] },
        { t = 11.14, text = [=[The party gathered in a circle and said his name, and the Index replied that the Licensed Summoning Liaison was, regrettably, on leave.]=] },
        { t = 20.78, text = [=[Zennit spent the week doing nothing at all, which he had always suspected to be the correct amount.]=] },
    },
    [13] = {
        { t = 0.41, text = [=[The following week, the group won.]=] },
        { t = 3.79, text = [=[Nobody was more surprised than the group.]=] },
        { t = 7.79, text = [=[The Index counted the summons, and the places, and the refusals, and found that the party had finished ahead of Zennit, despite his head start, and despite a run of dice that had, until then, been entirely reliable.]=] },
        { t = 21.87, text = [=[The Index checked the sum three times.]=] },
        { t = 25.84, text = [=[It was not wrong.]=] },
    },
    [14] = {
        { t = 0.40, text = [=[A victory for persistence, as the rules had promised.]=] },
        { t = 5.04, text = [=[The party celebrated in the traditional manner, by summoning Zennit to the celebration.]=] },
        { t = 11.13, text = [=[He arrived, as he always did, slightly confused, and was handed a small cake, which he did not trust.]=] },
        { t = 18.53, text = [=[The Index recorded the week as a narrow win for hope over paperwork, and began, quietly, to count the next one.]=] },
    },
    [15] = {
        { t = 0.41, text = [=[Zennit's second week off began, as these things do, with a parcel.]=] },
        { t = 5.58, text = [=[Inside was a brass key, a luggage tag that said Side Door, and a note that said, helpfully, nothing.]=] },
        { t = 13.07, text = [=[He checked the key against his secret list.]=] },
        { t = 17.06, text = [=[It was the first item.]=] },
        { t = 20.08, text = [=[It had been the first item all along, and he had been too busy being summoned to read it.]=] },
    },
    [16] = {
        { t = 0.41, text = [=[The side door of the Index was exactly where the key said it would be, behind the letter Q, between a filing cabinet and a sign that said Please Do Not.]=] },
        { t = 10.73, text = [=[Zennit went in.]=] },
        { t = 13.13, text = [=[Beyond it was a quiet corridor, a very old kettle, and a desk with a chair that fit him suspiciously well.]=] },
        { t = 21.00, text = [=[He did not sit down.]=] },
        { t = 23.72, text = [=[He ticked the first item on his list, and somewhere in the Index, a clerk cleared his throat.]=] },
    },
    [17] = {
        { t = 0.42, text = [=[The group's second win arrived with an unexpected receipt.]=] },
        { t = 5.51, text = [=[Tucked into the cake box, under the napkins, was a sheet of faint blue carbon paper, which, held up to the light, showed the cover of a form.]=] },
        { t = 15.03, text = [=[The title was smudged.]=] },
        { t = 17.91, text = [=[The number was not.]=] },
        { t = 20.66, text = [=[It was Form 27B slash 6, or at least the part that had pressed through to the next page.]=] },
    },
    [18] = {
        { t = 0.40, text = [=[Scholars had always maintained that the form did not exist.]=] },
        { t = 5.35, text = [=[The carbon copy suggested otherwise.]=] },
        { t = 9.46, text = [=[It suggested that the form had once been filled in, by someone, in triplicate, and that the other two copies had gone to the Index and to the Ritual of Summoning.]=] },
        { t = 20.06, text = [=[The party kept the third.]=] },
        { t = 23.07, text = [=[The Index asked for it back.]=] },
        { t = 26.39, text = [=[The party said they would think about it.]=] },
    },
}
-- introHighlights: while something is mentioned, a box is drawn round it (x, y, w, h in the 960x540 picture).
ST.introHighlights = {
    [1] = {
        { t = 0.65, x = 684, y = 244, w = 222, h = 297 },
        { t = 16.71, x = 322, y = 344, w = 120, h = 158 },
        { t = 20.11, x = 322, y = 344, w = 120, h = 158 },
    },
    [2] = {
        { t = 1.72, x = 612, y = 192, w = 216, h = 156 },
        { t = 2.36, x = 30, y = 10, w = 380, h = 520 },
    },
    [3] = {
        { t = 5.05, x = 696, y = 56, w = 208, h = 300 },
        { t = 16.56, x = 26, y = 166, w = 198, h = 216 },
        { t = 19.95, x = 246, y = 166, w = 198, h = 216 },
        { t = 24.39, x = 466, y = 166, w = 198, h = 216 },
    },
    [4] = {
        { t = 4.90, x = 108, y = 128, w = 272, h = 380 },
        { t = 9.65, x = 690, y = 140, w = 140, h = 185 },
    },
    [5] = {
        { t = 1.33, x = 250, y = 20, w = 460, h = 500 },
        { t = 14.51, x = 730, y = 50, w = 170, h = 140 },
        { t = 19.22, x = 30, y = 324, w = 210, h = 226 },
    },
    [6] = {
        { t = 3.54, x = 244, y = 30, w = 472, h = 480 },
        { t = 5.46, x = 26, y = 224, w = 176, h = 240 },
    },
    [7] = {
        { t = 1.65, x = 50, y = 224, w = 520, h = 236 },
        { t = 3.93, x = 754, y = 124, w = 212, h = 290 },
        { t = 8.56, x = 556, y = 226, w = 200, h = 260 },
    },
    [8] = {
        { t = 1.09, x = 344, y = 0, w = 376, h = 524 },
        { t = 5.01, x = 640, y = 50, w = 150, h = 200 },
        { t = 11.81, x = 24, y = 374, w = 132, h = 172 },
    },
    [9] = {
        { t = 4.83, x = 36, y = 56, w = 236, h = 278 },
        { t = 7.33, x = 36, y = 356, w = 456, h = 78 },
        { t = 9.39, x = 376, y = 356, w = 112, h = 78 },
        { t = 14.92, x = 500, y = 50, w = 240, h = 400 },
        { t = 24.58, x = 36, y = 56, w = 448, h = 278 },
    },
    [10] = {
        { t = 2.57, x = 36, y = 96, w = 272, h = 380 },
        { t = 7.88, x = 326, y = 86, w = 188, h = 258 },
        { t = 11.43, x = 516, y = 86, w = 188, h = 258 },
        { t = 16.16, x = 706, y = 86, w = 188, h = 258 },
        { t = 23.24, x = 326, y = 356, w = 426, h = 140 },
    },
    [11] = {
        { t = 1.80, x = 40, y = 60, w = 440, h = 270 },
        { t = 14.00, x = 262, y = 140, w = 220, h = 170 },
        { t = 17.05, x = 50, y = 365, w = 150, h = 100 },
        { t = 22.85, x = 500, y = 50, w = 240, h = 400 },
    },
    [12] = {
        { t = 2.13, x = 24, y = 110, w = 176, h = 150 },
        { t = 7.36, x = 296, y = 26, w = 392, h = 60 },
        { t = 13.36, x = 340, y = 140, w = 170, h = 66 },
        { t = 19.25, x = 556, y = 104, w = 182, h = 84 },
        { t = 21.97, x = 766, y = 200, w = 170, h = 280 },
    },
    [13] = {
        { t = 1.63, x = 540, y = 120, w = 330, h = 250 },
        { t = 13.52, x = 40, y = 60, w = 440, h = 270 },
        { t = 15.85, x = 262, y = 140, w = 220, h = 170 },
        { t = 17.45, x = 50, y = 365, w = 150, h = 100 },
    },
    [14] = {
        { t = 0.48, x = 176, y = 22, w = 608, h = 86 },
        { t = 6.67, x = 90, y = 140, w = 360, h = 230 },
        { t = 15.34, x = 232, y = 306, w = 118, h = 100 },
        { t = 16.70, x = 550, y = 140, w = 250, h = 350 },
        { t = 24.53, x = 822, y = 350, w = 106, h = 160 },
    },
    [15] = {
        { t = 3.75, x = 50, y = 190, w = 290, h = 230 },
        { t = 6.39, x = 396, y = 140, w = 250, h = 120 },
        { t = 7.25, x = 396, y = 286, w = 190, h = 100 },
        { t = 10.48, x = 610, y = 262, w = 140, h = 128 },
        { t = 15.03, x = 40, y = 30, w = 220, h = 140 },
        { t = 17.91, x = 40, y = 30, w = 220, h = 140 },
    },
    [16] = {
        { t = 4.77, x = 396, y = 70, w = 186, h = 400 },
        { t = 6.70, x = 36, y = 196, w = 128, h = 272 },
        { t = 8.01, x = 176, y = 142, w = 208, h = 72 },
        { t = 15.33, x = 612, y = 396, w = 106, h = 80 },
        { t = 16.72, x = 696, y = 290, w = 240, h = 190 },
    },
    [17] = {
        { t = 6.45, x = 36, y = 296, w = 270, h = 190 },
        { t = 9.82, x = 372, y = 52, w = 276, h = 356 },
        { t = 15.28, x = 396, y = 86, w = 228, h = 70 },
        { t = 21.47, x = 396, y = 200, w = 228, h = 100 },
    },
    [18] = {
        { t = 3.12, x = 50, y = 50, w = 760, h = 150 },
        { t = 13.25, x = 50, y = 50, w = 760, h = 150 },
        { t = 16.67, x = 90, y = 290, w = 440, h = 170 },
        { t = 20.73, x = 590, y = 170, w = 310, h = 240 },
        { t = 23.77, x = 46, y = 436, w = 328, h = 72 },
        { t = 27.83, x = 586, y = 436, w = 328, h = 72 },
    },
}
