-- Generated by tools/intro/build_ledger_audio.py. Do not edit by hand; rerun it after changing LINES in Ledger.lua.
-- The length in seconds of each recorded line of "The Index today" (Media/ledger/<id>.ogg).
local ADDON, ST = ...
ST.ledgerClips = {
    recap_z1 = 5.60,
    recap_z2 = 6.40,
    recap_z3 = 6.70,
    recap_z4 = 5.30,
    recap_g1 = 4.50,
    recap_g2 = 7.20,
    recap_g3 = 7.10,
    recap_g4 = 6.90,
    last_zennit = 10.60,
    last_group = 10.70,
    empty_first = 7.60,
    empty_fresh = 4.60,
    wait = 3.18,
    end_both = 7.20,
    end_group = 6.90,
    end_zennit = 4.90,
    week_leave = 9.00,
    week_closed = 8.40,
    week_none = 6.90,
    evidence = 4.00,
}
