-- Generated by tools/intro/build_tour_audio.py. Do not edit by hand; rerun it after changing LINES in Tour.lua.
-- The length in seconds of each recording of the tour (Media/tour/<id>.ogg).
local ADDON, ST = ...
ST.tourClips = {
    hello = 15.00,
    nothing_new = 13.60,
    caster = 12.20,
    z_nothing_new = 13.50,
    window = 12.90,
    season = 13.20,
    week = 8.50,
    party = 9.90,
    tally = 6.90,
    zennit = 10.70,
    z_party = 10.00,
    z_zennit = 12.80,
    log = 6.80,
    story = 11.60,
    sync = 10.80,
    tools = 8.60,
    writ = 12.60,
    status = 6.60,
    commands = 15.20,
    goodbye = 12.80,
}
