"""Render the lines of the tour (/sc tour) with the Zennit narrator recipe.

The sentences live in the LINES table of Tour.lua (one id = "sentence" per line). This reads them, renders each with
.claude/skills/zenit-narrator-audio/scripts/render_takes.py (same voice, same processing as the intro), copies the
clips to Media/tour/<id>.ogg and writes their lengths to TourClips.lua, which the tour uses to time each step.

    python tools/intro/build_tour_audio.py              # every line
    python tools/intro/build_tour_audio.py --only hello,goodbye
    python tools/intro/build_tour_audio.py --stale      # only the lines whose sentence changed since they were rendered

Run it again after changing a sentence in LINES, then fully restart WoW (a /reload does not pick up new media).
Needs the same things as render_takes.py (Python with sherpa-onnx, soundfile, numpy; ffmpeg; the Kokoro model).
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
RENDER = os.path.join(ROOT, ".claude", "skills", "zenit-narrator-audio", "scripts", "render_takes.py")
sys.path.insert(0, os.path.dirname(RENDER))

import narration_source as ns   # the sentences, how they are spoken, and the SRC_HASH tag the renderer stamps


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="comma-separated line ids to render")
    ap.add_argument("--stale", action="store_true", help="render only the lines whose sentence or recipe changed")
    args = ap.parse_args()

    spoken = ns.tour_speech()
    ids = ns.stale_ids("tour") if args.stale else args.only.split(",") if args.only else list(spoken)
    if args.stale and not ids:
        return print("every tour clip is up to date")
    unknown = [i for i in ids if i not in spoken]
    if unknown:
        sys.exit("not in Tour.lua LINES: " + ", ".join(unknown))

    out_dir = os.path.join(ROOT, "Media", "tour")
    os.makedirs(out_dir, exist_ok=True)
    work = tempfile.mkdtemp(prefix="tour_")
    numbers = {200 + n: i for n, i in enumerate(ids, 1)}   # render_takes numbers its takes; use 201, 202, ...
    extra = os.path.join(work, "lines.txt")
    with open(extra, "w", encoding="utf-8") as f:
        for n, i in numbers.items():
            f.write("%d|%s\n" % (n, spoken[i]))
    env = dict(os.environ, PYTHONIOENCODING="utf-8")
    subprocess.run([sys.executable, RENDER, "--only", ",".join(map(str, numbers)), "--extra", extra, "--out", work],
                   check=True, env=env)
    for n, i in numbers.items():
        shutil.copyfile(os.path.join(work, "narrator_backstory_%d_rp.ogg" % n), ns.tour_path(i))

    # lengths of every clip now in the folder (not just this run's), so --only keeps the manifest whole
    ffmpeg = ns.find_ffmpeg()
    lengths = {}
    for i in spoken:
        path = ns.tour_path(i)
        if not os.path.exists(path):
            continue
        info = subprocess.run([ffmpeg, "-hide_banner", "-i", path], capture_output=True, text=True).stderr
        h, m, s = re.search(r"Duration: (\d+):(\d+):([\d.]+)", info).groups()
        lengths[i] = int(h) * 3600 + int(m) * 60 + float(s)

    manifest = ["-- Generated by tools/intro/build_tour_audio.py. Do not edit by hand; rerun it after changing LINES in Tour.lua.",
                "-- The length in seconds of each recording of the tour (Media/tour/<id>.ogg).",
                "local ADDON, ST = ...", "ST.tourClips = {"]
    manifest += ["    %s = %.2f," % (i, lengths[i]) for i in spoken if i in lengths]
    manifest.append("}")
    with open(os.path.join(ROOT, "TourClips.lua"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(manifest) + "\n")
    print("%d clips in Media/tour, %d rendered this run; TourClips.lua written" % (len(lengths), len(ids)))


if __name__ == "__main__":
    main()
