"""Render the recorded lines of "The Index today" (the Ledger scene) with the Zennit narrator recipe.

The fixed sentences live in the LINES table of Ledger.lua (one id = "sentence" per line). This reads them, renders
each with .claude/skills/zenit-narrator-audio/scripts/render_takes.py (same voice, same processing), copies the
clips to Media/ledger/<id>.ogg and writes their lengths to LedgerClips.lua, which the viewer uses to time the scene.

    python tools/intro/build_ledger_audio.py              # every line
    python tools/intro/build_ledger_audio.py --only wait,evidence
    python tools/intro/build_ledger_audio.py --stale      # only the lines whose sentence changed since they were rendered

Run it again after changing a sentence in LINES, then fully restart WoW (a /reload does not pick up new media).
Needs the same things as render_takes.py (Python with sherpa-onnx, soundfile, numpy; ffmpeg; the Kokoro model).
"""
import argparse
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
RENDER = os.path.join(ROOT, ".claude", "skills", "zenit-narrator-audio", "scripts", "render_takes.py")
sys.path.insert(0, os.path.dirname(RENDER))

import narration_source as ns   # the sentences, how they are spoken, and the SRC_HASH tag the renderer stamps


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="comma-separated line ids to render")
    ap.add_argument("--stale", action="store_true", help="render only the lines whose sentence or recipe changed")
    args = ap.parse_args()

    # whole lines (LINES) and the short fragments a spliced line is made of (FRAGMENTS, and the numbers 0-99)
    spoken = dict(ns.ledger_speech())
    fragment_ids = set(ns.fragment_speech())
    spoken.update(ns.fragment_speech())
    everything = list(spoken)
    ids = ns.stale_ids("ledger") + ns.stale_ids("fragment") if args.stale else args.only.split(",") if args.only else everything
    if args.stale and not ids:
        return print("every ledger clip is up to date")
    unknown = [i for i in ids if i not in spoken]
    if unknown:
        sys.exit("not in Ledger.lua LINES or FRAGMENTS: " + ", ".join(unknown))

    out_dir = os.path.join(ROOT, "Media", "ledger")
    os.makedirs(out_dir, exist_ok=True)
    work = tempfile.mkdtemp(prefix="ledger_")
    numbers = {100 + n: i for n, i in enumerate(ids, 1)}   # render_takes numbers its takes; use 101, 102, ...
    extra = os.path.join(work, "lines.txt")
    with open(extra, "w", encoding="utf-8") as f:
        for n, i in numbers.items():
            f.write("%d|%s\n" % (n, spoken[i]))
    env = dict(os.environ, PYTHONIOENCODING="utf-8")
    frag_numbers = ",".join(str(n) for n, i in numbers.items() if i in fragment_ids)
    subprocess.run([sys.executable, RENDER, "--only", ",".join(map(str, numbers)), "--extra", extra, "--out", work,
                    "--fragments", frag_numbers], check=True, env=env)

    import render_takes
    ffmpeg = render_takes.find_ffmpeg()
    for n, i in numbers.items():
        take = os.path.join(work, "narrator_backstory_%d_rp.ogg" % n)
        dest = os.path.join(out_dir, i + ".ogg")
        with open(take, "rb") as a, open(dest, "wb") as b:
            b.write(a.read())

    # lengths of every clip now in the folder (not just this run's), so --only keeps the manifest whole
    lengths = {}
    for i in everything:
        path = os.path.join(out_dir, i + ".ogg")
        if not os.path.exists(path):
            continue
        info = subprocess.run([ffmpeg, "-hide_banner", "-i", path], capture_output=True, text=True).stderr
        h, m, s = re.search(r"Duration: (\d+):(\d+):([\d.]+)", info).groups()
        lengths[i] = int(h) * 3600 + int(m) * 60 + float(s)

    manifest = ["-- Generated by tools/intro/build_ledger_audio.py. Do not edit by hand; rerun it after changing LINES or FRAGMENTS in Ledger.lua.",
                "-- The length in seconds of each recording of \"The Index today\" (Media/ledger/<id>.ogg): whole lines, then the short",
                "-- fragments a spliced line is made of (their lengths are exact, with no silence at either end).",
                "local ADDON, ST = ...", "ST.ledgerClips = {"]
    manifest += ["    %s = %.3f," % (i, lengths[i]) if i in fragment_ids else "    %s = %.2f," % (i, lengths[i])
                 for i in everything if i in lengths]
    manifest.append("}")
    with open(os.path.join(ROOT, "LedgerClips.lua"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(manifest) + "\n")
    print("%d clips in Media/ledger, %d rendered this run; LedgerClips.lua written" % (len(lengths), len(ids)))


if __name__ == "__main__":
    main()
