# Scans Media\clips\*.ogg and writes ClipList.lua, the list of clip files the addon knows about
# (AddOns cannot list a folder at run time). Run it after adding or removing clips, then /reload.
#
# Names must look like <category>_<NN>_<who>.ogg, e.g. wag_01_aaron, zenit_land_02_sam,
# zenit_refuse_03_sam, ritual_02_lewis, narrator_weekopen_01_lewis.
#   powershell -ExecutionPolicy Bypass -File tools\build_clip_manifest.ps1
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$dir = Join-Path $root "Media\clips"
New-Item -ItemType Directory -Force $dir | Out-Null

$good = @()
$bad = @()
foreach ($f in Get-ChildItem -LiteralPath $dir -Filter *.ogg | Sort-Object Name) {
    $name = [IO.Path]::GetFileNameWithoutExtension($f.Name)
    if ($name -match '^(.+?)_(\d+)_(.+)$' -and $name -match '^[A-Za-z0-9_\-]+$') { $good += $name } else { $bad += $f.Name }
}

$lines = @(
    "-- Generated by tools/build_clip_manifest.ps1. Do not edit by hand; rerun the script after changing Media/clips.",
    "local ADDON, ST = ...",
    "ST.clipFiles = {"
)
foreach ($n in $good) { $lines += "    `"$n`"," }
$lines += "}"
[IO.File]::WriteAllText((Join-Path $root "ClipList.lua"), (($lines -join "`n") + "`n"))

"{0} clip(s) listed in ClipList.lua" -f $good.Count
$good | ForEach-Object { ($_ -replace '^(.+?)_\d+_.+$', '$1') } | Group-Object | Sort-Object Name | ForEach-Object { "  {0}: {1}" -f $_.Name, $_.Count }
if ($bad.Count -gt 0) {
    Write-Warning ("Skipped (name must be <category>_<NN>_<who>.ogg, letters, digits, - and _ only): " + ($bad -join ", "))
}
